from typing import Tuple, List
from ..models.book import Book
from ..models.character import Character
from ..models.style import StyleConfig
from nova_agent.llm.client_base import LLMClient


class StoryPlanner:
    """阶段2：故事结构设计
    
    设计三幕结构，分配内容到各页"""
    
    def __init__(self, llm_client: LLMClient):
        self.llm = llm_client
    
    def plan(
        self,
        title: str,
        theme: str,
        character: Character,
        style: StyleConfig,
        target_age: Tuple[int, int],
        total_pages: int = 24,
    ) -> Book:
        """规划故事结构"""
        
        prompt = self._build_prompt(title, theme, character, target_age, total_pages)
        response = self.llm.complete(prompt, temperature=0.7)
        
        return self._parse_response(response, title, theme, character, style, target_age, total_pages)
    
    def _build_prompt(
        self, title: str, theme: str, character: Character, age: Tuple[int, int], pages: int
    ) -> str:
        age_str = f"{age[0]}-{age[1]}岁"
        return f"""你是儿童绘本故事策划师。请为《{title}》设计故事结构，总共{pages}页。

故事主题：{theme}
主角：{character.name}, {character.age}岁, {character.personality}, {character.appearance}
适合年龄：{age_str}

儿童绘本故事通常是三幕结构：
- 开头（第1-6页）：介绍主角和背景，引出问题
- 发展（第7-18页）：主角展开探索，遇到挑战
- 结尾（第19-{pages}页）：解决问题，得到成长，点题

请为每一页设计内容要点，每页一句话说明。按照以下JSON格式输出：

{{
  "plan": [
    {{
      "page_number": 1,
      "content_summary": "这一页的内容要点（一句话）"
    }},
    ...
  ]
}}

只输出JSON，不要其他内容：
"""
    
    def _parse_response(
        self, response: str, title: str, theme: str, character: Character, 
        style: StyleConfig, target_age: Tuple[int, int], total_pages: int
    ) -> Book:
        import json
        try:
            if "```json" in response:
                response = response.split("```json")[1].split("```")[0]
            elif "```" in response:
                response = response.split("```")[1]
            
            data = json.loads(response.strip())
            
            # 这里只创建Book框架，pages稍后由storyboard_writer填充
            from ..models.book import Book
            from ..models.page import Page
            
            pages_list = []
            for item in data["plan"]:
                page = Page(
                    page_number=item["page_number"],
                    text="",  # 稍后填充
                    scene_description=item["content_summary"],
                    image_prompt="",  # 稍后填充
                )
                pages_list.append(page)
            
            book = Book(
                title=title,
                author="AI Generated by Nova Agent",
                target_age_range=target_age,
                total_pages=len(pages_list),
                main_character=character,
                style=style,
                pages=pages_list,
                theme=theme,
            )
            
            return book
            
        except Exception as e:
            raise ValueError(f"Failed to parse story plan: {e}\nResponse: {response}")
